In [152]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [153]:
dataset = pd.read_csv("Life Expectancy Data.csv")

In [154]:
dataset

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [155]:
df = dataset.iloc[:,3:]
df

,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [156]:
print(df.isna().any())
df.shape

Life expectancy                     True
Adult Mortality                     True
infant deaths                      False
Alcohol                             True
percentage expenditure             False
Hepatitis B                         True
Measles                            False
 BMI                                True
under-five deaths                  False
Polio                               True
Total expenditure                   True
Diphtheria                          True
 HIV/AIDS                          False
GDP                                 True
Population                          True
 thinness  1-19 years               True
 thinness 5-9 years                 True
Income composition of resources     True
Schooling                           True
dtype: bool

(2938, 19)

In [159]:
for i in df.columns:
    cl_mean = df[i].mean()
    print(cl_mean)
    df_filled = df.fillna(cl_mean)
df_filled

69.22493169398912
164.79644808743168
30.303948264125257
4.6028607871720375
738.2512954533823
80.94046121593291
2419.5922396187884
38.32124655647373
42.0357385976855
82.55018842069202
5.9381895280235915
82.32408359027065
1.7421034717494939
7483.158469138481
12753375.120052498
4.8397038567493205
4.870316804407711
0.6275510645976166
11.992792792792786

,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [160]:
print(df_filled.isna().any())

Life expectancy                    False
Adult Mortality                    False
infant deaths                      False
Alcohol                            False
percentage expenditure             False
Hepatitis B                        False
Measles                            False
 BMI                               False
under-five deaths                  False
Polio                              False
Total expenditure                  False
Diphtheria                         False
 HIV/AIDS                          False
GDP                                False
Population                         False
 thinness  1-19 years              False
 thinness 5-9 years                False
Income composition of resources    False
Schooling                          False
dtype: bool

In [161]:
df.iloc[:,3:]
df_mean = df.mean()

In [162]:
df.fillna(df['Life expectancy '].mode())

,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [164]:
df_filled.isnull().any()

Life expectancy                    False
Adult Mortality                    False
infant deaths                      False
Alcohol                            False
percentage expenditure             False
Hepatitis B                        False
Measles                            False
 BMI                               False
under-five deaths                  False
Polio                              False
Total expenditure                  False
Diphtheria                         False
 HIV/AIDS                          False
GDP                                False
Population                         False
 thinness  1-19 years              False
 thinness 5-9 years                False
Income composition of resources    False
Schooling                          False
dtype: bool

In [172]:
df.dtypes
rdf = df_filled.round(decimals = 3)
rdf

,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,65.0,263.0,62,0.01,71.280,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259,33736494.0,17.2,17.3,0.479,10.1
1,59.9,271.0,64,0.01,73.524,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.697,327582.0,17.5,17.5,0.476,10.0
2,59.9,268.0,66,0.01,73.219,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.745,31731688.0,17.7,17.7,0.470,9.9
3,59.5,272.0,69,0.01,78.184,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959,3696958.0,17.9,18.0,0.463,9.8
4,59.2,275.0,71,0.01,7.097,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,44.3,723.0,27,4.36,0.000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.367,12777511.0,9.4,9.4,0.407,9.2
2934,44.5,715.0,26,4.06,0.000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351,12633897.0,9.8,9.9,0.418,9.5
2935,44.8,73.0,25,4.43,0.000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348,125525.0,1.2,1.3,0.427,10.0
2936,45.3,686.0,25,1.72,0.000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587,12366165.0,1.6,1.7,0.427,9.8
2937,46.0,665.0,24,1.68,0.000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.359,12222251.0,11.0,11.2,0.434,9.8

In [173]:
X = rdf.iloc[:,1:].values
X

array([[2.63e+02, 6.20e+01, 1.00e-02, ..., 1.73e+01, 4.79e-01, 1.01e+01],
       [2.71e+02, 6.40e+01, 1.00e-02, ..., 1.75e+01, 4.76e-01, 1.00e+01],
       [2.68e+02, 6.60e+01, 1.00e-02, ..., 1.77e+01, 4.70e-01, 9.90e+00],
       ...,
       [7.30e+01, 2.50e+01, 4.43e+00, ..., 1.30e+00, 4.27e-01, 1.00e+01],
       [6.86e+02, 2.50e+01, 1.72e+00, ..., 1.70e+00, 4.27e-01, 9.80e+00],
       [6.65e+02, 2.40e+01, 1.68e+00, ..., 1.12e+01, 4.34e-01, 9.80e+00]])

In [174]:
y = rdf.iloc[:, 1].values

In [175]:
y

array([263., 271., 268., ...,  73., 686., 665.])

In [176]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.3, random_state=1)

In [177]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [178]:
X_train

array([[ 1.31851768, -0.19776464, -0.89078677, ...,  0.98099311,
        -0.3364362 , -2.01792122],
       [-0.60171886, -0.23112498,  0.51577651, ..., -0.89351238,
        -0.19103976,  0.98402141],
       [-0.9283981 ,  0.30264038, -0.95787613, ..., -0.28373348,
        -0.33935142, -0.7443698 ],
       ...,
       [ 0.99183844, -0.21444481, -0.58541448, ...,  0.73256467,
        -0.33789381, -0.92630572],
       [ 0.66515919, -0.23946506,  1.61234065, ..., -0.53216192,
        -0.22784437,  0.65047223],
       [ 0.20302758, -0.15606422, -0.70802608, ..., -0.82575917,
        -0.25954736, -0.41082062]])

In [179]:
regressor = RandomForestRegressor(n_estimators=20, random_state=1)

In [180]:
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=20, random_state=1)

In [181]:
y_pred = np.round(regressor.predict(X_test))
y_pred

array([ 61., 363., 229., 218., 655.,  63., 158., 168., 164.,  76.,  17.,
        68., 450., 332., 195., 277.,  92., 177., 254., 418., 151.,  12.,
       129., 344.,  84.,  73.,  16., 228., 222., 356., 167., 464.,   9.,
       157.,  96., 138., 235.,  62., 123., 163., 133.,  79., 145., 277.,
       256., 133., 242., 146., 134., 284.,  48., 128., 141., 560., 194.,
        22.,  25.,  16.,  33., 277., 383., 566., 275., 217.,  16., 131.,
       157.,  36.,  84., 226.,  86.,  68., 221.,  71., 179.,  82.,  19.,
        99.,  12.,  56., 179.,  18., 176.,   7., 312.,  22., 183.,   6.,
       129., 189.,  56., 144., 229.,  61., 116.,  22., 321.,  95., 189.,
       168., 188.,  12., 236., 186., 218., 328.,  12., 527.,  37., 185.,
       125., 223., 151.,  57., 278., 297., 149., 172.,  11., 176., 175.,
       115., 259., 166., 216.,  21., 123.,  19., 228., 225.,  76.,  72.,
        34.,  25., 134., 142., 222., 119.,   4., 297., 145., 282., 428.,
        69., 237., 467., 218., 326., 668., 139., 121.,  85., 113., 238.,
       298., 134., 174., 136., 286.,  78., 161.,  32.,  89., 374., 393.,
       131., 115.,  32.,  26., 219.,  12., 245., 163., 565., 174., 259.,
       141.,  66., 237., 193.,  57., 174., 183., 182., 154., 271., 117.,
        29.,  73., 285.,  66.,  75., 199.,  49.,  44., 182., 488.,  18.,
        98., 214., 158., 213., 144., 178., 299., 185.,  92.,  59.,  48.,
       444., 182., 138.,  63., 128., 154., 121., 284., 124., 174.,  73.,
       144., 122., 143., 137., 167., 263., 235., 186., 122., 227., 288.,
       157.,  79.,  67., 252., 143.,  95., 132., 251., 281.,  14., 224.,
       226.,   8., 116.,  76., 149., 283., 116., 157.,  85., 139., 131.,
       146.,  27.,  88.,  68., 277., 169., 189., 117.,  83.,  14., 237.,
        77.,  83., 175., 171.,  59.,  87.,  12.,  12.,  83., 294.,  29.,
       188., 169., 279., 167., 145., 286., 138.,  14.,  77.,  12., 415.,
       159., 166., 263.,  73., 266., 225., 118., 141., 495., 155., 166.,
       253., 221.,  74.,  16., 370., 163., 137.,  65., 384., 292., 161.,
        25.,  24.,  11., 412., 113., 588., 219.,  86., 162., 149., 217.,
        99.,  16., 267.,  19., 238., 142., 178., 149., 158., 149., 334.,
       111., 428., 216., 276., 371., 172., 356., 224.,  16., 224.,  41.,
        15., 199., 276., 238., 155., 119.,   2.,  85., 427.,   8., 158.,
       274., 212.,   3., 242., 213.,  66.,  11., 183., 148., 350.,  71.,
        13., 198., 137., 251.,  65.,  99., 256., 274., 155.,   9., 137.,
         3., 393., 339., 271., 217.,  45.,  53., 126., 165., 172.,  74.,
       134., 145.,  75., 295., 383.,  16.,  17., 144., 144., 185.,  17.,
       165.,  34.,  72., 228., 116., 223.,  45.,  99.,  58.,  76., 132.,
       383.,  12.,  66., 219.,  76., 168., 152., 148.,  11.,  68., 174.,
       221., 460., 169.,  15., 347.,  66., 348.,  81., 176., 237., 192.,
        17.,   7.,  11.,  21., 123.,  54.,  19., 144., 139., 142., 366.,
       114., 323., 622., 146., 138., 211., 154., 366., 278., 427., 397.,
       217., 129.,   7., 328.,  89., 151., 211., 356., 161., 283., 283.,
        93., 137., 196., 181., 134., 147.,  88., 292., 272., 249., 385.,
       196., 272., 179.,  48., 226.,  78., 251., 413., 297.,  97., 192.,
        75.,  89.,  85., 178., 147., 699., 355., 178.,  12.,  73., 284.,
       122., 166., 251.,   6., 436., 132., 148.,  58., 224.,  22., 164.,
       135.,  11., 144., 129.,  38., 241., 224.,  85.,  81., 118., 263.,
        87., 127., 189.,  86., 123.,  67.,  94.,  81., 267., 179.,  89.,
        81., 183.,  15.,  94.,  96., 147.,  41., 271., 152., 339.,  61.,
       144., 189., 431., 136., 436., 161., 138., 295., 259.,  21.,  19.,
       147.,  15., 232.,  61., 373.,  29., 263.,  78., 173., 286., 527.,
        19.,  77., 178., 187., 357.,   6., 163., 394.,  16., 138., 298.,
       279.,  12.,   7.,  66., 172., 336.,  11., 129.,  86.,  82.,  57.,
       153., 133., 126., 488., 281., 271., 138.,  12.,  16., 162., 189.,
       242., 159.,  94., 221., 119., 347.,  85.,  65.,  89.,  11.,  94.,
       177.,  25., 141.,  44., 273., 527., 272.,  74., 157., 157., 176.,
       276.,  15.,  16.,  89., 369., 138., 283., 188.,  81., 198., 194.,
        23., 139.,  78., 378., 436., 385.,  11., 126., 268.,  97., 156.,
       168.,  46., 131., 268.,  13., 287., 123., 375.,  98., 229., 183.,
       176.,  24., 361., 266.,  76., 232., 168.,  98.,  71., 148.,  38.,
       215., 123., 131., 197., 141., 126., 163., 128., 296., 113., 153.,
        26., 137., 328.,  71.,  18.,  13., 214., 144.,  87., 161., 154.,
        64., 417., 119., 177., 146., 376., 177., 113.,   8., 129., 313.,
       227., 411.,  99.,  83.,  58., 344.,  16., 128., 222.,  14., 146.,
       168.,  21.,  99.,  16.,  24.,  66., 135., 322., 159., 442., 225.,
       179., 116.,   8.,  82.,  93.,  97., 221.,   1.,  81.,  14., 493.,
        92., 491., 218., 212.,  12., 118.,  75., 177., 188., 122., 187.,
        14.,  18.,  79., 363., 132., 269.,  14., 373., 183.,  62.,  41.,
        33., 591., 174., 217., 184.,  56., 189., 123., 288., 168., 143.,
        71.,  22., 286., 157., 187., 127.,  97., 217., 372., 123.,  75.,
       427., 118.,  79., 331.,  96., 163.,  48.,  88.,  19.,   1., 134.,
       158., 217.,  23., 189.,  82., 138., 179.,  78.,  23., 256.,  49.,
        74.,  22.,  63., 129.,   9., 145., 347.,  12., 147., 184.,  34.,
        26., 357., 288.,  67.,  96., 314., 338., 296., 193., 211., 195.,
        53.,  26.,  17.,  72., 126., 259.,  23., 289., 143.,  13., 452.,
       162.,  21., 443.,  72., 156., 195., 191., 112., 133., 325., 428.,
       171., 248., 221., 706.,  14., 297.,  15., 179.,   2., 139., 124.,
       113.,  19., 228., 178., 121., 142., 174., 325., 194.,  84., 221.,
       183., 514.,  93., 148., 172.,  68.,  29., 129.,  91., 242., 126.,
       472.,  69., 138.,  94., 323., 375., 186.,  75., 172.,  83., 127.,
       237., 328.])